const TYPES = {
  PRODUCTS: {
    FETCH: 'PRODUCTS_FETCH_REQUESTED',
    SUCCESS: 'PRODUCTS_FETCH_SUCCESS',
    FAIL: 'PRODUCTS_FETCH_FAIL'
  },
  PRODUCT: {
    FETCH: 'PRODUCT_FETCH_REQUESTED',
    SUCCESS: 'PRODUCT_FETCH_SUCCESS',
    FAIL: 'PRODUCT_FETCH_FAIL'
  }
};

export default TYPES;
